[project]
authors = ["fgvieira <1151762+fgvieira@users.noreply.github.com>"]
channels = ["conda-forge", "bioconda"]
name = "prune_graph"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
rust = ">=1.85.0,<1.86"
